// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package wallet_repository

import (
	"database/sql"
	"time"
)

type Wallet struct {
	UserID    string       `json:"user_id"`
	Name      string       `json:"name"`
	PublicKey string       `json:"public_key"`
	Mnemonic  string       `json:"mnemonic"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
